---
title: "Figure 3C. Leveraging universal infant growth and maternal nutritional signals to identify putative growth-associated biomarkers of mammary gland dysfunction"
---

```{r setup, include=FALSE}
# Show code if file is knit 
knitr::opts_chunk$set(echo = TRUE)

# Sets working directory to file location
library(rstudioapi)
if (interactive() && rstudioapi::isAvailable()) { 
  rootdir = dirname(rstudioapi::getSourceEditorContext()$path) 
  setwd(dirname(rstudioapi::getSourceEditorContext()$path)) 
}
```

# Load data, libraries, functions
``` {r}
# Load libraries and data 
source("plotting_setup.R")
# Load functions
source("plotting_functions.R")
```

## Figure 3C 
``` {r}
# Full set of features for the supplementary figure
select_feats_full = c('Cit','Bio','K','Creatinine','Lys','LSTb','PA','B1','B2',
                 'HipAcid','C5','AABA','PC.ae.C34.0','LNnT','Se','FLNH',
                 'TG.16.1_36.1.','TG.18.2_36.0.', "X6.SL", "Mn", "p.Cresol.SO4", 'B6', 'LNFP.III', 'g.tocopherol', 'X3.SL')
# Selected features to highlight in main figure (see Figure S4 for full feature set)
select_feats = c('C5', 'Se', 'X6.SL', 'Bio', 'PA', 'B2',  'AABA', 'LNnT') 

# Key to convert column names to full feature names
nutrient_heatmap_key = list("rLC_neg_mtb_5483668"="Adrenic Acid",
                              "rLC_neg_mtb_2059251"="2-Hydroxyisovaleric Acid",
                              "PA" = "Pantothenic Acid",
                              "Bio" = "Biotin",
                              "Sia"="Sialylated HMOs",
                              "Se"="Selenium",
                              "Asp" = "Aspartate",
                              "g.tocopherol" ="γ-Tocopherol",
                              "HipAcid" = "Hippuric Acid",
                              "B2" = "Vitamin B2",
                              "X6.SL" = "6'-Sialyllactose",
                              "LNFP.III" = "LNFP III",
                              "Thr" = "Threonine",
                              "AABA" = "α-Aminobutyric acid",
                              "Fuc" = "Fucosylated HMOs",
                              "Mn" = "Manganese",
                              "C5" = "Valerylcarnitine (C5)",
                              "Ind.SO4" = "Indoxyl Sulfate",
                              "Phe" = "Phenylalanine",
                              "B6" = "Vitamin B6",
                              "B1" = "Vitamin B1",
                              "p.Cresol.SO4" = "p-Cresol Sulfate",
                              "Met.SO" = "Methionine Sulfate",
                              "Ca" = "Calcium",
                              "PC.ae.C34.0" = "Phosphatidylcholine (34:0)",
                              "lysoPC.a.C18.0" = "Lysophosphatidylcholine (18:0)",
                              "SM.C18.1" = "Sphingomyelin (18:1)",
                              "TG.17.2_38.5." = "Triacylglyceride (17:2/38:5)",
                              "TG.20.3_32.2." = "Triacylglyceride (29:3/32:2)",
                              "HexCer.d18.1.18.1." = "Hexosylceramide (d18:1/18:1)",
                              "LNnT" = "LNnT",
                              "K" = "Potassium", 
                              "Cit" = "Citrulline",
                              "Lys" = "Lysine",
                              "TG.16.1_36.1" = "Triacylglyceride (16:1/36.1)",
                              "TG.18.2_36.0" = "Triacylglyceride (18:2/36.0)",
                              "X3.SL" = "3'-Siayllactose")

# Growth velocity calculations for Misame
misame_weight_diff_df <- left_join(misame_metadata, inner_join(
  misame_metadata %>% filter(VISIT=="Delivery", is.na(VISIT_R_FL)) %>%dplyr::select(SUBJID, WTKG) %>% dplyr::rename(wt_0=WTKG),
  misame_metadata %>% filter(VISIT=="Post Natal FU M03", is.na(VISIT_R_FL)) %>%dplyr::select(SUBJID, WTKG, AGEDAYS) %>% dplyr::rename(wt_3=WTKG, AGE=AGEDAYS))) %>%
    mutate(delta_weight_3mo = wt_3-wt_0,
           growth_vel_3mo=(1000*log(wt_3/wt_0))/AGE) %>%dplyr::select(SUBJIDO, growth_vel_3mo) %>%
  dplyr::rename(SubjectID=SUBJIDO)  

# Growth velocity Calculations for Vital (Mumta)
vital_weight_diff_df <- left_join(vital_metadata, inner_join(
  vital_metadata %>% filter(VISIT=="Baseline", is.na(VISIT_R_FL)) %>%dplyr::select(SUBJID, WTKG) %>%dplyr::rename(wt_0=WTKG),
  vital_metadata %>% filter(VISIT=="Follow up month 3", is.na(VISIT_R_FL)) %>%dplyr::select(SUBJID, WTKG, AGEDAYS) %>%dplyr::rename(wt_3=WTKG, AGE=AGEDAYS))) %>%
    mutate(delta_weight_3mo = wt_3-wt_0,
           growth_vel_3mo=(1000*log(wt_3/wt_0))/AGE) %>%dplyr::select(SUBJIDO, growth_vel_3mo) %>%
  dplyr::rename(SubjectID=SUBJIDO) 

# MISAME Feature-feature correlations calculated using Spearman (Hmisc::rcorr)
M_corr_nutrients_1_unsupp = Misame_everything %>%
  left_join(misame_weight_diff_df) %>%
  filter(Timepoint==1, BEP==0) %>%
  dplyr::select(growth_vel_3mo, select_feats_full) %>% as.matrix() %>% rcorr(type = "spearman")
M_corr_nutrients_2_unsupp = Misame_everything %>%
  left_join(misame_weight_diff_df) %>%
  filter(Timepoint==2, BEP==0) %>%
  dplyr::select(growth_vel_3mo, select_feats_full) %>% as.matrix() %>% rcorr(type = "spearman")
M_corr_nutrients_3_unsupp = Misame_everything %>%
  left_join(misame_weight_diff_df) %>%
  filter(Timepoint==3, BEP==0) %>%
  dplyr::select(growth_vel_3mo, select_feats_full) %>% as.matrix() %>% rcorr(type = "spearman")

# Extracting and formatting associations between growth velocity and top features for MISAME
Misame_corr_nutrients_unsupp = left_join(corr_to_heatmap_df(M_corr_nutrients_1_unsupp$r, "growth_vel_3mo", "14-21D"),
                                  left_join(corr_to_heatmap_df(M_corr_nutrients_2_unsupp$r, "growth_vel_3mo", "1-2M"),
                                            corr_to_heatmap_df(M_corr_nutrients_3_unsupp$r, "growth_vel_3mo", "3-4M"))) %>% convert_nutrients_heatmap(nutrient_heatmap_key)
Misame_corr_nutr_unsupp_pval = left_join(corr_to_heatmap_df(M_corr_nutrients_1_unsupp$P, "growth_vel_3mo", "14-21D"),
                                  left_join(corr_to_heatmap_df(M_corr_nutrients_2_unsupp$P, "growth_vel_3mo", "1-2M"),
                                            corr_to_heatmap_df(M_corr_nutrients_3_unsupp$P, "growth_vel_3mo", "3-4M"))) %>% convert_nutrients_heatmap(nutrient_heatmap_key)

# Vital (Mumta) Feature-feature correlations calculated using Spearman (Hmisc::rcorr)
V_corr_nutrients_1_unsupp = Vital_everything %>%
  left_join(vital_weight_diff_df) %>%
  filter(Timepoint==1, BEP==0) %>%
  dplyr::select(growth_vel_3mo, select_feats_full) %>% as.matrix() %>% rcorr(type = "spearman")
V_corr_nutrients_2_unsupp = Vital_everything %>%
  left_join(vital_weight_diff_df) %>%
  filter(Timepoint==2, BEP==0) %>%
  dplyr::select(growth_vel_3mo, select_feats_full) %>% as.matrix() %>% rcorr(type = "spearman")

# Extracting and formatting associations between growth velocity and top features for Mumta
Vital_corr_nutrients_unsupp = left_join(corr_to_heatmap_df(V_corr_nutrients_1_unsupp$r, "growth_vel_3mo", "40D"),
                                 corr_to_heatmap_df(V_corr_nutrients_2_unsupp$r, "growth_vel_3mo", "56D")) %>% convert_nutrients_heatmap(nutrient_heatmap_key) 
Vital_corr_nutr_unsupp_pval = left_join(corr_to_heatmap_df(V_corr_nutrients_1_unsupp$P, "growth_vel_3mo", "40D"),
                                 corr_to_heatmap_df(V_corr_nutrients_2_unsupp$P, "growth_vel_3mo", "56D")) %>% convert_nutrients_heatmap(nutrient_heatmap_key) 

# Calculating and extracting associations for CHILD
C_corr_nutrients_1_unsupp = Child_everything %>%
  filter(Timepoint==1) %>%
  dplyr::select(growth_vel_3mo, select_feats_full) %>% as.matrix() %>% rcorr(type = "spearman")

Child_corr_nutrients_unsupp = corr_to_heatmap_df(C_corr_nutrients_1_unsupp$r, "growth_vel_3mo", "3M") %>% convert_nutrients_heatmap(nutrient_heatmap_key) 
Child_corr_nutr_unsupp_pval = corr_to_heatmap_df(C_corr_nutrients_1_unsupp$P, "growth_vel_3mo", "3M") %>% convert_nutrients_heatmap(nutrient_heatmap_key) 

M_heatmap_unsupp = Misame_corr_nutrients_unsupp[unlist(nutrient_heatmap_key[select_feats]),] %>%
  Heatmap(
    cluster_rows = FALSE, cluster_columns = FALSE, column_names_centered = TRUE, 
    col = colorRamp2(seq(-0.5, 0.5, length.out = 101), colorRampPalette(c("purple", "white", "forestgreen"))(101)),
    name = "Rho", show_heatmap_legend = FALSE,
    column_title = "MISAME", column_names_rot = 0,
    show_column_names = TRUE, show_row_names = FALSE, 
    cell_fun = function(j, i, x, y, width, height, fill) {
      pval = Misame_corr_nutr_unsupp_pval[i, j] 
      if (pval < 0.05) {
        text_label <- round(Misame_corr_nutrients_unsupp[i, j], 2)
      } else {
        text_label <- "ns"
      }
      grid.text(text_label, x, y, gp = gpar(fontsize = 10, col = "black"))
    }
)
V_heatmap_unsupp = Vital_corr_nutrients_unsupp[unlist(nutrient_heatmap_key[select_feats]),] %>%
  Heatmap(
    cluster_rows = FALSE, cluster_columns = FALSE,  
    col = colorRamp2(seq(-0.5, 0.5, length.out = 101), colorRampPalette(c("purple", "white", "forestgreen"))(101)),
    name = "Rho", show_heatmap_legend = FALSE,
    column_title = "Mumta-LW", column_names_rot = 0, column_names_centered = TRUE,
    show_column_names = TRUE, show_row_names = TRUE, 
    cell_fun = function(j, i, x, y, width, height, fill) {
      pval = Vital_corr_nutr_unsupp_pval[i, j] 
      if (pval < 0.05) {
        text_label <- round(Vital_corr_nutrients_unsupp[i, j], 2)
      } else {
        text_label <- "ns"
      }
      grid.text(text_label, x, y, gp = gpar(fontsize = 10, col = "black"))
    }
)


Figure3C = ggarrange(as.ggplot(M_heatmap_unsupp), as.ggplot(V_heatmap_unsupp), nrow = 1, widths = c(1,1.2))
Figure3C
ggexport(filename = paste0(fig_path, "/Figure3C.pdf"),
         plot = Figure3C,
        width = 5.3, height = 4)
```

