---
title: "Figure S4. Growth velocity associations with growth and nutrition-associated features in unsupplemented mothers"
---

```{r setup, include=FALSE}
# Show code if file is knit 
knitr::opts_chunk$set(echo = TRUE)

# Sets working directory to file location
library(rstudioapi)
if (interactive() && rstudioapi::isAvailable()) { 
  rootdir = dirname(rstudioapi::getSourceEditorContext()$path) 
  setwd(dirname(rstudioapi::getSourceEditorContext()$path)) 
}
```

# Load data, libraries, functions
``` {r}
# Load libraries and data 
source("plotting_setup.R")
# Load functions
source("plotting_functions.R")
```

# Supplementary Figure S4

Requires objects from Figure 3C 
``` {r}
# Knitting Figure 3 document to load data
knit_dir = ".knitR"
if (!dir.exists(knit_dir)) { dir.create(knit_dir, recursive = TRUE) }
knit_Figure3 = paste0(knit_dir, "/Figure3.R")
if (!file.exists(knit_Figure3)) {
    knitr::purl(
    input = "Figure3.Rmd",
    output = knit_Figure3,
    documentation = 1
    )
}
# Loading figure 3 data 
source(knit_Figure3)
```
``` {r}
M_heatmap_unsupp_full = Misame_corr_nutrients_unsupp %>%
  Heatmap(
    cluster_rows = FALSE, cluster_columns = FALSE, column_names_centered = TRUE, 
    col = colorRamp2(seq(-0.5, 0.5, length.out = 101), colorRampPalette(c("purple", "white", "forestgreen"))(101)),
    name = "Rho", show_heatmap_legend = FALSE,
    column_title = "MISAME", column_names_rot = 0,
    show_column_names = TRUE, show_row_names = FALSE, 
    cell_fun = function(j, i, x, y, width, height, fill) {
      pval = Misame_corr_nutr_unsupp_pval[i, j] 
      if (pval < 0.05) {
        text_label <- round(Misame_corr_nutrients_unsupp[i, j], 2)
      } else {
        text_label <- "ns"
      }
      grid.text(text_label, x, y, gp = gpar(fontsize = 10, col = "black"))
    }
)
V_heatmap_unsupp_full = Vital_corr_nutrients_unsupp %>%
  Heatmap(
    cluster_rows = FALSE, cluster_columns = FALSE,  
    col = colorRamp2(seq(-0.5, 0.5, length.out = 101), colorRampPalette(c("purple", "white", "forestgreen"))(101)),
    name = "Rho", show_heatmap_legend = FALSE,
    column_title = "Mumta-LW", column_names_rot = 0, column_names_centered = TRUE,
    show_column_names = TRUE, show_row_names = TRUE, 
    cell_fun = function(j, i, x, y, width, height, fill) {
      pval = Vital_corr_nutr_unsupp_pval[i, j] 
      if (pval < 0.05) {
        text_label <- round(Vital_corr_nutrients_unsupp[i, j], 2)
      } else {
        text_label <- "ns"
      }
      grid.text(text_label, x, y, gp = gpar(fontsize = 10, col = "black"))
    }
)
FigureS4 = ggarrange(as.ggplot(M_heatmap_unsupp_full), as.ggplot(V_heatmap_unsupp_full), nrow = 1, widths = c(1,1.3))
FigureS4
ggexport(filename = paste0(fig_path, "/S4.pdf"),
         plot = FigureS4,
        width = 7.5, height = 6, dpi = 600)
```
