---
title: "Figure S8. Biomarkers Identified in our Study Capture Tight Junction Integrity Signals in HM"
---

```{r setup, include=FALSE}
# Show code if file is knit 
knitr::opts_chunk$set(echo = TRUE)

# Sets working directory to file location
library(rstudioapi)
if (interactive() && rstudioapi::isAvailable()) { 
  rootdir = dirname(rstudioapi::getSourceEditorContext()$path) 
  setwd(dirname(rstudioapi::getSourceEditorContext()$path)) 
}
```

# Load data, libraries, functions
``` {r}
# Load libraries and data 
source("plotting_setup.R")
# Load functions
source("plotting_functions.R")
```

## Figure S8A
``` {r}
Na_K_plot_feats = list("Na_K_Ratio" = "Na:K Ratio",
                       "Na" = "Sodium",
                       "C2" = "Acetylcarnitine (C2)",
                       "C3" = "Propionylcarnitine (C3)",
                       "C4" = "Butyrylcarnitine (C4)",
                       "C5" = "Valerylcarnitine (C5)",
                       "Lys" = "Lysine",
                       "Se"="Selenium",
                       "X6.SL" = "6'-Sialyllactose")

Na_K_corr_list = list("MISAME" = Misame_everything %>% 
                        filter(Timepoint==2, 
                               SampleID %in% rownames(misame_proteomics_filt_genes)) %>% 
                        dplyr::select(names(Na_K_plot_feats)) %>% 
                        as.matrix() %>% rcorr(type = "spearman"),
                      "Mumta-LW" = Vital_everything %>% 
                        filter(Timepoint==2, SampleID %in% rownames(vital_proteomics_filt_genes)) %>% 
                        dplyr::select(names(Na_K_plot_feats)) %>% 
                        as.matrix() %>% rcorr(type = "spearman"))
Na_K_plots = list()
Na_K_matricies = list()
for (study in names(Na_K_corr_list)) {
  Na_K_corr = Na_K_corr_list[[study]]
  Na_K_corr_Rho = Na_K_corr$r[, names(Na_K_plot_feats)[c(-1, -2)]] %>% as.data.frame() %>% dplyr::slice(1:2)
  Na_K_corr_p = Na_K_corr$P[, names(Na_K_plot_feats)[c(-1, -2)]] %>% as.data.frame() %>% dplyr::slice(1:2)
  Na_K_matricies[[study]]  = Na_K_corr_Rho
  Na_K_plots[[study]] = Na_K_corr_Rho %>% 
    Heatmap(
        cluster_rows = FALSE, cluster_columns = FALSE,  
                col = colorRamp2(seq(-1, 1, length.out = 101), colorRampPalette(c("purple", "white", "forestgreen"))(101)),
                name = "Rho", 
                column_title = study, column_names_rot = -45,
                row_labels = unlist(Na_K_plot_feats[c(1, 2)]),
                column_labels = unlist(Na_K_plot_feats[c(-1, -2)]),
                cell_fun = function(j, i, x, y, width, height, fill) {
                  pval = Na_K_corr_p[i, j]
                  if (is.na(pval)) {
                     text_label <- "NA"
                  } else if (pval < 0.05) {
                    text_label <- round(Na_K_corr_Rho[i, j], 2)
                  } else {
                    text_label <- "ns"
                  }
                  grid.text(text_label, x, y, gp = gpar(fontsize = 10, col = "black"))
                }
      ) %>% as.ggplot()
}
FigureS8A = ggarrange(plotlist = Na_K_plots) 
FigureS8A 
ggexport(filename = paste0(fig_path, "/FigureS8A.pdf"), 
         plot = FigureS8A,
        width = 8, height = 2.5)
```

## Figure S8B
``` {r}
Misame_everything=Misame_everything %>% mutate(BEPyn=ifelse(Postnatal_BEP==TRUE, "Y", "N"))
Vital_everything=Vital_everything %>% mutate(BEPyn=ifelse(Postnatal_BEP==TRUE, "Y", "N"))

FigureS8B = ggarrange(
  ggarrange(
    Misame_everything %>% filter(Timepoint==1) %>% mutate(Label="14-21D") %>%
      ggplot(aes(x=BEPyn, y=Na, fill=Postnatal_BEP))  + ylab("Sodium (uM)") + geom_boxplot(show.legend = FALSE) + facet_grid(.~Label) + 
      stat_compare_means(comparisons = list(c("Y", "N")), 
                         method = "wilcox", label = "p.signif") + 
      ggtitle("MISAME") + xlab("Postnatal BEP") + theme_minimal(),
    Misame_everything %>% filter(Timepoint==2) %>%  mutate(Label="1-2M") %>%
      ggplot(aes(x=BEPyn, y=Na, fill=Postnatal_BEP)) + ylab(NULL) + geom_boxplot(show.legend = FALSE) + facet_grid(.~Label) + 
      stat_compare_means(comparisons = list(c("Y", "N")), 
                         method = "wilcox", label = "p.signif") + 
      ggtitle("") + xlab("Postnatal BEP") + theme_minimal(),
    Misame_everything %>% filter(Timepoint==3) %>% mutate(Label="3-4M") %>%
      ggplot(aes(x=BEPyn, y=Na, fill=Postnatal_BEP)) + ylab(NULL) + geom_boxplot(show.legend = FALSE) + facet_grid(.~Label) + 
      stat_compare_means(comparisons = list(c("Y", "N")), 
                         method = "wilcox", label = "p.signif") + 
      ggtitle("") + xlab("Postnatal BEP") + theme_minimal(),
    Vital_everything %>% filter(Timepoint==1) %>% mutate(Label="42D") %>%
      ggplot(aes(x=BEPyn, y=Na, fill=Postnatal_BEP)) + ylab(NULL) + geom_boxplot(show.legend = FALSE) + facet_grid(.~Label) + 
      stat_compare_means(comparisons = list(c("Y", "N")), 
                         method = "wilcox", label = "p.signif") +
      ggtitle("VITAL") + xlab("Postnatal BEP") + theme_minimal(),
    Vital_everything %>% filter(Timepoint==2) %>% mutate(Label="56D") %>%
      ggplot(aes(x=BEPyn, y=Na, fill=Postnatal_BEP)) + ylab(NULL) + geom_boxplot(show.legend = FALSE) + facet_grid(.~Label) + 
      stat_compare_means(comparisons = list(c("Y", "N")), 
                         method = "wilcox", label = "p.signif") + 
      ggtitle("") + xlab("Postnatal BEP") + theme_minimal(),
    nrow=1),
  ggarrange(
    Misame_everything %>% filter(Timepoint==1) %>% mutate(Label="14-21D") %>%
      ggplot(aes(x=BEPyn, y=Na_K_Ratio, fill=Postnatal_BEP)) + ylab("Na:K Ratio") + geom_boxplot(show.legend = FALSE) + facet_grid(.~Label) + 
      stat_compare_means(comparisons = list(c("Y", "N")), 
                         method = "wilcox", label = "p.signif") +
      ggtitle("MISAME") + xlab("Postnatal BEP") + theme_minimal(),
    Misame_everything %>% filter(Timepoint==2) %>%  mutate(Label="1-2M") %>%
      ggplot(aes(x=BEPyn, y=Na_K_Ratio, fill=Postnatal_BEP)) + ylab(NULL) + geom_boxplot(show.legend = FALSE) + facet_grid(.~Label) + 
      stat_compare_means(comparisons = list(c("Y", "N")), 
                         method = "wilcox", label = "p.signif") +
      ggtitle("") + xlab("Postnatal BEP") + theme_minimal(),
    Misame_everything %>% filter(Timepoint==3) %>% mutate(Label="3-4M") %>%
      ggplot(aes(x=BEPyn, y=Na_K_Ratio, fill=Postnatal_BEP)) + ylab(NULL) + geom_boxplot(show.legend = FALSE) + facet_grid(.~Label) + 
      stat_compare_means(comparisons = list(c("Y", "N")), 
                         method = "wilcox", label = "p.signif") + 
      ggtitle("") + xlab("Postnatal BEP") + theme_minimal(),
    Vital_everything %>% filter(Timepoint==1) %>% mutate(Label="42D") %>%
      ggplot(aes(x=BEPyn, y=Na_K_Ratio, fill=Postnatal_BEP)) + ylab(NULL) + geom_boxplot(show.legend = FALSE) + facet_grid(.~Label) + 
      stat_compare_means(comparisons = list(c("Y", "N")), 
                         method = "wilcox", label = "p.signif") + 
      ggtitle("VITAL") + xlab("Postnatal BEP") + theme_minimal(),
    Vital_everything %>% filter(Timepoint==2) %>% mutate(Label="56D") %>%
      ggplot(aes(x=BEPyn, y=Na_K_Ratio, fill=Postnatal_BEP)) + ylab(NULL) + geom_boxplot(show.legend = FALSE) + facet_grid(.~Label) + 
      stat_compare_means(comparisons = list(c("Y", "N")), 
                         method = "wilcox", label = "p.signif") +
      ggtitle("") + xlab("Postnatal BEP") + theme_minimal(),
    nrow=1),
  ggarrange(
    Misame_everything %>% filter(Timepoint==1) %>% mutate(Label="14-21D") %>%
      ggplot(aes(x=BEPyn, y=K, fill=Postnatal_BEP)) + ylab("Potassium (uM)") + geom_boxplot(show.legend = FALSE) + facet_grid(.~Label) + 
      stat_compare_means(comparisons = list(c("Y", "N")), 
                         method = "wilcox", label = "p.signif") + 
      ggtitle("MISAME") + xlab("Postnatal BEP") + theme_minimal(),
    Misame_everything %>% filter(Timepoint==2) %>%  mutate(Label="1-2M") %>%
      ggplot(aes(x=BEPyn, y=K, fill=Postnatal_BEP)) + ylab(NULL) + geom_boxplot(show.legend = FALSE) + facet_grid(.~Label) + 
      stat_compare_means(comparisons = list(c("Y", "N")), 
                         method = "wilcox", label = "p.signif") + 
      ggtitle("") + xlab("Postnatal BEP") + theme_minimal(),
    Misame_everything %>% filter(Timepoint==3) %>% mutate(Label="3-4M") %>%
      ggplot(aes(x=BEPyn, y=K, fill=Postnatal_BEP)) + ylab(NULL) + geom_boxplot(show.legend = FALSE) + facet_grid(.~Label) + 
      stat_compare_means(comparisons = list(c("Y", "N")), 
                         method = "wilcox", label = "p.signif") +
      ggtitle("") + xlab("Postnatal BEP") + theme_minimal(),
    Vital_everything %>% filter(Timepoint==1) %>% mutate(Label="42D") %>%
      ggplot(aes(x=BEPyn, y=K, fill=Postnatal_BEP)) + ylab(NULL) + geom_boxplot(show.legend = FALSE) + facet_grid(.~Label) + 
      stat_compare_means(comparisons = list(c("Y", "N")), 
                         method = "wilcox", label = "p.signif") + 
      ggtitle("VITAL") + xlab("Postnatal BEP") + theme_minimal(),
    Vital_everything %>% filter(Timepoint==2) %>% mutate(Label="56D") %>%
      ggplot(aes(x=BEPyn, y=K, fill=Postnatal_BEP)) + ylab(NULL) + geom_boxplot(show.legend = FALSE) + facet_grid(.~Label) + 
      stat_compare_means(comparisons = list(c("Y", "N")), 
                         method = "wilcox", label = "p.signif") + 
      ggtitle("") + xlab("Postnatal BEP") + theme_minimal(),
    nrow=1), ncol = 1)
FigureS8B
ggexport(FigureS8B, filename=paste0(fig_path, "/FigureS8B.pdf"),
         width=7.65, height=9)
```


